[project]
name = "yandex-scooter-playwright"
version = "1.0.0"
description = "UI test framework based on Playwright"
readme = "README.md"
authors = [
    { name = "Kirill-Kamyshanov", email = "nestor10000@mail.ru" }
]
requires-python = ">=3.14"
dependencies = [
    "allure-pytest==2.16.0",
    "dateparser==1.4.1",
    "playwright==1.62.0",
    "pre-commit>=4.6.2",
    "pytest==9.1.1",
    "pytest-playwright==0.8.0",
    "pytest-rerunfailures==16.4",
    "pytest-timeout==2.4.0",
    "pytest-xdist==3.8.0",
]


[tool.pytest.ini_options]
minversion = "8.0"
testpaths = ["tests"]
markers = [
    "smoke: проверка ключевой функциональности",
    "regression: все тесты для полной проверки приложения"
]

addopts = [
    "--alluredir=allure-results",
    "-n=3",
    "--reruns=2",
    "--reruns-delay=1",
    "--timeout=60"
    ]


[tool.ruff]
line-length = 120
target-version = "py314"
extend-exclude = ["venv", "allure-results", ".pytest_cache"]

[tool.ruff.lint]
select = [
    "E",    # Ошибки PEP8 (лишние пробелы, неправильные отступы)
    "W",    # Предупреждения PEP8 (Лишние пустые строки)
    "F",    # Неиспользуемые импорты/переменные
    "I",    # Сортировка импортов
    "B",    # Потенциальные баги (assert False)
    "UP",   # Устаревший синтаксис (type вместо isinstanse)
    "RUF",  # ruff-specific
    "SIM",  # flake8-simplify
    "C4",   # flake8-comprehensions
]
ignore = [
    "B008",    # function call in default arg (Pydantic Field)
    "RUF001",  # cyrillic ambiguous chars (тексты на русском)
    "RUF002",
    "RUF003",
]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["S101"]  # assert allowed in tests

[tool.ruff.format]
quote-style = "double"