[pytest]

markers =
    smoke: проверка ключевой функциональности
    regression: все тесты для полной проверки приложения

addopts =
    --alluredir=allure-results
;    -n=3
    --reruns=2
    --reruns-delay=1
    --timeout=60